[package]
name = "boilerplate_template"
version = "1.0.0"
authors = []

[addresses]
module_addr = "_"

[dependencies]
AptosFramework = { local = "/home/rohan/aptos-core/aptos-move/framework/aptos-framework", rev = "testnet"}

[dev-dependencies]
